import type { Metadata } from "next";
import { Database, ScrollText, ShieldCheck, Users } from "lucide-react";
import { SiteHeader } from "@/components/landing/SiteHeader";
import { SiteFooter } from "@/components/landing/SiteFooter";
import { siteConfig } from "@/config/site";
import { buildBreadcrumbSchema } from "@/lib/seo/schema";

export const metadata: Metadata = {
  title: "About Us",
  description: `The mission and methodology behind ${siteConfig.name}, an independent dental implant cost calculator.`,
  alternates: { canonical: "/about" },
};

const principles = [
  {
    icon: Database,
    title: "Reference pricing, not guesswork",
    description:
      "Our cost model is built from configurable per-country, per-city, per-brand, and per-procedure pricing tiers that we periodically review against published price-transparency data and industry fee surveys, rather than a single hardcoded average.",
  },
  {
    icon: ScrollText,
    title: "We explain every number",
    description:
      "Every estimate comes with a plain-language breakdown of exactly which inputs — location, treatment type, implant tier, add-ons, insurance, financing — contributed to each line item.",
  },
  {
    icon: ShieldCheck,
    title: "Independent, not pay-to-play",
    description:
      "We are not owned by, and do not accept payment from, any dental clinic, implant manufacturer, or financing provider to influence the pricing shown.",
  },
  {
    icon: Users,
    title: "Built for patients researching options",
    description:
      "This tool exists to help people compare the rough shape of implant costs across locations and treatment types before they ever set foot in a clinic — not to replace a real consultation.",
  },
];

export default function AboutPage() {
  const jsonLd = buildBreadcrumbSchema([
    { name: "Home", url: siteConfig.url },
    { name: "About", url: `${siteConfig.url}/about` },
  ]);

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <SiteHeader />
      <main className="flex-1">
        <section className="px-4 py-16 sm:px-6 sm:py-24 lg:px-8">
          <div className="mx-auto max-w-3xl">
            <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
              About {siteConfig.name}
            </h1>
            <div className="legal-prose mt-8">
              <p>
                {siteConfig.name} is an independent, self-serve calculator that gives people a
                realistic, itemized estimate of what dental implant treatment is likely to cost —
                based on where they live, which treatment and implant tier they&rsquo;re
                considering, and their insurance and financing situation.
              </p>
              <p>
                Dental implant pricing is notoriously opaque: quotes vary wildly between clinics,
                countries, and even the same procedure described in different terms. We built this
                tool because we think people should be able to get a grounded starting estimate in
                under a minute, for free, before they ever talk to a sales team — and understand
                exactly why the number is what it is.
              </p>
              <h2>How our estimates are built</h2>
              <p>
                Every estimate is generated by a rules-based pricing engine, not a single average
                number. It combines a base treatment fee, an implant-brand-and-material cost, a
                location multiplier (country, state/region, and city), optional add-on procedures,
                your insurance coverage, and your financing terms into one itemized result. The
                underlying reference figures are maintained in a structured pricing configuration
                that we periodically review and update.
              </p>
              <h2>What we are not</h2>
              <p>
                We are not a dental clinic, a network of providers, or a licensed source of medical
                or financial advice, and no estimate produced here is a binding quote. Read our{" "}
                <a href="/disclaimer">Disclaimer</a> for the full picture, and always confirm
                actual pricing and treatment suitability with a licensed dentist or oral surgeon.
              </p>
            </div>
          </div>
        </section>

        <section className="bg-surface-muted px-4 py-16 sm:py-20">
          <div className="mx-auto max-w-6xl">
            <h2 className="text-center text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              What guides how we build this
            </h2>
            <div className="mt-10 grid gap-6 sm:grid-cols-2">
              {principles.map((p) => (
                <div key={p.title} className="rounded-2xl bg-surface p-6 shadow-premium">
                  <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50">
                    <p.icon className="h-5 w-5 text-brand-600" aria-hidden="true" />
                  </span>
                  <h3 className="mt-4 font-semibold text-foreground">{p.title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-foreground-muted">
                    {p.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="px-4 py-16 sm:py-20">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Get in touch
            </h2>
            <p className="mt-3 text-foreground-muted">
              Questions, corrections to our pricing data, or partnership inquiries — we&rsquo;d
              like to hear from you.
            </p>
            <a
              href={`mailto:${siteConfig.contact.email}`}
              className="focus-ring mt-5 inline-block rounded-lg text-brand-600 underline underline-offset-2 hover:text-brand-700"
            >
              {siteConfig.contact.email}
            </a>
          </div>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
